config/routes.rb
Rails.application.routes.draw do
  get 'invitations/index'

  resources :invitations
  
  root 'invitations#index'  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invitation.rb
class Invitation < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

   def index
		@invitations = Invitation.all
	end

   def new
		@invitation = Invitation.new
   end

	def show
	end
    
	def create
		all_emails = params[:invitation][:all_emails]
		message = params[:invitation][:message]
		valid = true
		@invalids = []
		all_emails.split(/\s+|(\s*,\s*)/).each do |email|
			valid = false unless(email =~ /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)
		end
		if valid
			all_emails.split(/\s+|(\s*,\s*)/).each do |email|
				raw_parameters = {:email => email, :message => message}
				parameters = ActionController::Parameters.new(raw_parameters)
				@invitation = Invitation.new(parameters.permit(:email, :message))
				@invitation.save
			end
			redirect_to @invitation
		else
			all_emails.split(/\s+|(\s*,\s*)/).each do |email|
				@invalids.push(email) unless (email =~ /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)
			end
			raw_parameters = {:email => all_emails, :message => message}
			parameters = ActionController::Parameters.new(raw_parameters)
			@invitation = Invitation.new(parameters.permit(:email, :message))
			render 'new'
		end
	end	

	private
		def inv_params
			params.require(:invitation).permit(:email,:message)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invitation_helper.rb
module InvitationHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/index.html.erb
<h1> Sent emails</h1>

<%= link_to 'New email', new_invitation_path %>

<table>
  <tr>
    <th>Receiver</th>
    <th>Message</th>
  </tr>
 
  <% @invitations.each do |invitation| %>
    <tr>
      <td><%= invitation.email %></td>
      <td><%= invitation.message %></td>
    </tr>
  <% end %>
</table>

app/views/invitations/new.html.erb
<h3> New Email </h3>
<p> 
    Enter a comma or space separated list of emails addresses you wish to invite.
</p>


<%= form_with scope: :invitation, url: invitations_path, local: true do |form| %>
  <p>
    <%= form.label :all_emails %><br>
    <%= form.text_area :all_emails, cols: "100", rows: "10" %>
  </p>


	<% if @invalids.try(:any?) %>
    <div id="error_explanation">
      <p style="color:red;">
        The following emails are not valid:
		</p>
      <ul>
        <% @invalids.each do |inv| %>
          <li style="color:red;"><%= inv %></li>
        <% end %>
      </ul>
      
    </div>
  <% end %>



  <p>
    Enter invitation text. This will be email that will be received to let these users 
    know what they are being invited to.
  </p>
  <p>
    <%= form.label :message %><br>
    <%= form.text_area :message, cols: "100", rows: "10" %>
  </p>
 
  <p>
    <%= form.submit "Invite Users" %>
	<%= link_to 'Cancel', invitations_path %>
  </p>
<% end %>

app/views/invitations/show.html.erb
<p>
Message sent!

<%= link_to 'New email', new_invitation_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>